// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MICourses.Models;

public partial class Achievment
{
    [Key]
    public int ID_Achievment { get; set; }

    [Required]
    [StringLength(150)]
    public string Name { get; set; }

    [Required]
    [StringLength(500)]
    public string Description { get; set; }

    public string Condition { get; set; }

    [InverseProperty("ID_AchievmentNavigation")]
    public virtual ICollection<Users_Achievment> Users_Achievments { get; set; } = new List<Users_Achievment>();
}