// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MICourses.Models;

public partial class Answer
{
    [Key]
    public int ID_Answer { get; set; }

    public int ID_Question { get; set; }

    [Required]
    [StringLength(500)]
    public string Text { get; set; }

    public bool Correct { get; set; }

    [ForeignKey("ID_Question")]
    [InverseProperty("Answers")]
    public virtual Question ID_QuestionNavigation { get; set; }
}