// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MICourses.Models;

public partial class Certificate
{
    [Key]
    public int ID_Certificate { get; set; }

    public int ID_User { get; set; }

    public int ID_Course { get; set; }

    [Column(TypeName = "date")]
    public DateTime CompletionDate { get; set; }

    [Required]
    public string CertificatePath { get; set; }

    [ForeignKey("ID_Course")]
    [InverseProperty("Certificates")]
    public virtual Course ID_CourseNavigation { get; set; }

    [ForeignKey("ID_User")]
    [InverseProperty("Certificates")]
    public virtual User ID_UserNavigation { get; set; }
}