// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MICourses.Models;

public partial class Comment
{
    [Key]
    public int ID_Comment { get; set; }

    public int ID_Lesson { get; set; }

    [Required]
    [StringLength(1000)]
    public string Text { get; set; }

    [Column(TypeName = "date")]
    public DateTime Data { get; set; }

    [ForeignKey("ID_Lesson")]
    [InverseProperty("Comments")]
    public virtual Lesson ID_LessonNavigation { get; set; }

    [InverseProperty("ID_CommentNavigation")]
    public virtual ICollection<Users_Comment> Users_Comments { get; set; } = new List<Users_Comment>();
}