// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MICourses.Models;

public partial class Question
{
    [Key]
    public int ID_Question { get; set; }

    public int ID_Test { get; set; }

    [Required]
    [StringLength(1000)]
    public string Text { get; set; }

    [InverseProperty("ID_QuestionNavigation")]
    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    [ForeignKey("ID_Test")]
    [InverseProperty("Questions")]
    public virtual Test ID_TestNavigation { get; set; }
}