// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MICourses.Models;

public partial class Users_Lesson
{
    [Key]
    public int ID_Users_Lessons { get; set; }

    public int ID_User { get; set; }

    public int ID_Lesson { get; set; }

    public bool Status { get; set; }

    [Column(TypeName = "date")]
    public DateTime CompletionDate { get; set; }

    [ForeignKey("ID_Lesson")]
    [InverseProperty("Users_Lessons")]
    public virtual Lesson ID_LessonNavigation { get; set; }

    [ForeignKey("ID_User")]
    [InverseProperty("Users_Lessons")]
    public virtual User ID_UserNavigation { get; set; }
}