// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MICourses.Models;

public partial class User
{
    [Key]
    public int ID_User { get; set; }

    [Required]
    [StringLength(50)]
    public string Login { get; set; }

    [Required]
    [StringLength(50)]
    public string Email { get; set; }

    [Required]
    [StringLength(50)]
    public string Password { get; set; }

    [Required]
    [StringLength(50)]
    public string Role { get; set; }

    public int Lvl { get; set; }

    [StringLength(50)]
    public string Surname { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string MiddleName { get; set; }

    [Column(TypeName = "date")]
    public DateTime? Birthday { get; set; }

    [StringLength(50)]
    public string PhoneNumber { get; set; }

    [StringLength(50)]
    public string Sex { get; set; }

    [InverseProperty("ID_UserNavigation")]
    public virtual ICollection<Certificate> Certificates { get; set; } = new List<Certificate>();

    [InverseProperty("ID_UserNavigation")]
    public virtual ICollection<Users_Achievment> Users_Achievments { get; set; } = new List<Users_Achievment>();

    [InverseProperty("ID_UserNavigation")]
    public virtual ICollection<Users_Comment> Users_Comments { get; set; } = new List<Users_Comment>();

    [InverseProperty("ID_UserNavigation")]
    public virtual ICollection<Users_Course> Users_Courses { get; set; } = new List<Users_Course>();

    [InverseProperty("ID_UserNavigation")]
    public virtual ICollection<Users_Lesson> Users_Lessons { get; set; } = new List<Users_Lesson>();

    [InverseProperty("ID_UserNavigation")]
    public virtual ICollection<Users_Test> Users_Tests { get; set; } = new List<Users_Test>();
}