// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MICourses.Models;

public partial class Users_Comment
{
    [Key]
    public int ID_Users_Comments { get; set; }

    public int ID_User { get; set; }

    public int ID_Comment { get; set; }

    public int Reply { get; set; }

    [ForeignKey("ID_Comment")]
    [InverseProperty("Users_Comments")]
    public virtual Comment ID_CommentNavigation { get; set; }

    [ForeignKey("ID_User")]
    [InverseProperty("Users_Comments")]
    public virtual User ID_UserNavigation { get; set; }
}